#!/usr/bin/env python3
"""warble mark v4 generator: the trill — a bold five-bar sound wave.

Five thick pills whose envelope sings "war-ble": rise to the main crest, dip,
second crest (the trill) toward the cyan end of the voice gradient. Deliberately
few bars and thick strokes so the mark stays legible at 18 pt in the menu bar.

Emits every canonical artwork from one geometry (never hand-edit the outputs):
  ../warble-mark.svg                                   color mark (brand)
  ../../apps/macos/Sources/Shared/Resources/warble_glyph.svg   monochrome template (menu bar)
  ../../apps/macos/Sources/Shared/Resources/warble_icon.svg    color mark (in-app surfaces)
  warble_appicon.svg                                   app icon composition (squircle)
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- geometry (100 x 100 canvas) ------------------------------------------
BAR_W = 14.0     # thick: 5 bars, not 12 — visibility first
GAP = 6.5
HEIGHTS = [32, 64, 96, 50, 78]   # the trill: rise, CREST, dip, second crest ("war-ble")
CY = 50.0        # bars are vertically centered

PITCH = BAR_W + GAP
total_w = len(HEIGHTS) * BAR_W + (len(HEIGHTS) - 1) * GAP
x0 = (100 - total_w) / 2

GRADIENT = '''  <defs>
    <linearGradient id="voice" x1="0" y1="1" x2="1" y2="0">
      <stop offset="0" stop-color="#1E5BFF"/>
      <stop offset="1" stop-color="#3CC6FF"/>
    </linearGradient>
  </defs>
'''

def bars() -> str:
    out = []
    r = BAR_W / 2
    for i, h in enumerate(HEIGHTS):
        x = x0 + i * PITCH
        y = CY - h / 2
        out.append(f'    <rect x="{x:.2f}" y="{y:.2f}" width="{BAR_W:.2f}" height="{h:.2f}" rx="{r:.2f}"/>')
    return "\n".join(out)

COMMENT = "warble mark v4: the trill — five thick sound-wave bars; the envelope rises, crests, dips, and crests again (war-ble). Generated by brand/source/gen_wave_mark.py"

def mark_svg(fill_open: str, fill_close: str = "</g>", defs: str = "") -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n'
            f'  <!-- {COMMENT} -->\n{defs}{fill_open}\n{bars()}\n  {fill_close}\n</svg>\n')

color = mark_svg('  <g fill="url(#voice)">', defs=GRADIENT)
mono = mark_svg('  <g fill="#000000">')

# App icon: Apple-grid squircle (824/1024, r≈185) on a TRANSPARENT canvas — the
# margin must stay alpha-0 (finder/dock supply the backdrop), never white.
appicon = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <!-- {COMMENT} -->
{GRADIENT}  <rect x="100" y="100" width="824" height="824" rx="185" fill="#07080C"/>
  <g transform="translate(262,262) scale(5)" fill="url(#voice)">
{bars()}
  </g>
</svg>
'''

OUT = {
    os.path.join(HERE, "..", "warble-mark.svg"): color,
    os.path.join(HERE, "..", "..", "apps", "macos", "Sources", "Shared", "Resources", "warble_glyph.svg"): mono,
    os.path.join(HERE, "..", "..", "apps", "macos", "Sources", "Shared", "Resources", "warble_icon.svg"): color,
    os.path.join(HERE, "warble_appicon.svg"): appicon,
}

for path, svg in OUT.items():
    with open(path, "w") as f:
        f.write(svg)
    print(f"wrote {os.path.relpath(path, os.path.join(HERE, '..', '..'))}")
